import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from '@/providers/SessionProvider';
import { getServerSession } from 'next-auth/next';
import { authOptions } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";
import { NotificationProvider } from '@/context/NotificationContext';

// Update the font configuration
const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "C1DC PCD System",
  description: "Generated by Cyber1defense Communication",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <NextAuthSessionProvider session={session}>
          <NotificationProvider>
          {children}
          <Toaster />
        </NotificationProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
